### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by otraore** [bronze1man/radius#10]
Following [godoc style documentation](https://blog.golang.org/godoc-documenting-go-code) would be a great addition.

**Comment by bronze1man** [comment]
@osiloke ,you can send a pull request to add this feature or fork it to do whatever you want.
I am not maintaining this package for now.

**Comment by Taherismail17** [comment]
@bronze1man how may I contact you privately

**Comment by bronze1man** [comment]
@Taherismail17 
Sorry, I will not leave my private contact information in public.

**Comment by Taherismail17** [comment]
Do you have Twitter?

**Comment by bronze1man** [comment]
@Taherismail17
Sorry again, I will not leave my private contact information in public.

**Comment by Taherismail17** [comment]
Ok, sorry I just had a few questions about X-VPN as it had many references to your GitHub

**Comment by bronze1man** [comment]
exnx26zz2@outlook.com
